development:
  adapter: postgresql
  encoding: unicode
  database: t20-dev
  pool: 5
  username: ak
  password: leAN

test:
  adapter: postgresql
  encoding: unicode
  database: t20-test
  pool: 5
  username: ak
  password: leAN

production:
  adapter: postgresql
  encoding: unicode
  database: t20-prod
  pool: 5
  username: ak
  password: leAN